# Generated by Django 5.2.8 on 2025-12-19 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='temp_images/')),
                ('original_filename', models.CharField(max_length=255)),
                ('expiry_duration', models.CharField(choices=[('1h', '1 Hour'), ('1d', '1 Day'), ('7d', '7 Days'), ('1m', '1 Month')], default='1d', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
