# Generated by Django 5.2.8 on 2025-12-21 16:15

import tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='image',
            field=models.ImageField(upload_to=tools.models.encrypted_upload_path),
        ),
    ]
